version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ~/data/mongo:/data/db
    ports:
      - "27017:27017"

  redis:
    container_name: redis1
    image: redis
    ports:
      - "6379:6379"

  java:
    container_name: java
    image: openjdk:8

  gcc:
    container_name: gcc
    image: gcc

  python:
    container_name: python
    image: python:2
