version: "2"
services:
  app:
    container_name: app
    image : shobhit1997/code_compiler
    restart: always
    build: .
    ports:
      - "8000:8000"
    links:
      - mongo
      - redis

  mongo:
    container_name: mongo1
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  redis:
    container_name: redis
    image: redis
